baseURL = 'https://queerlycollected.com/'
languageCode = 'en-us'
title = 'Queerly Collected'
theme = 'hugo-universal-theme'
themesDir = 'themes'


[caches]
  [caches.images]
    dir = ':cacheDir/images'